# Jekyll theme setting
theme: minimal-mistakes-jekyll
# remote_theme: "mmistakes/minimal-mistakes@4.24.0"
# Themes avaiable: "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise", "default"
minimal_mistakes_skin    : "contrast"

# Site settings
locale                   : "zh-CN"
title                    : "技术传播百态说"
title_separator          : "|"
# subtitle                 : site tagline that appears below site title in masthead
name                     : "王烨"
description              : "解密文档技术，精研技术写作，评说行业百态。"
url                      : "https://www.docsimpo.work"
# baseurl                  : "/awesome-technical-writing-learning"
repository               : "wongyah/docsimpo.work"
# teaser                   : path of fallback teaser image used in the "Related posts", e.g. "/assets/images/500x300.png"
logo: "/assets/images/logo/docsimpo-logo@2x.png"
# masthead_title           :  "docSimpo" # overrides the website title displayed in the masthead, use " " for no title
# breadcrumbs            : true # true, false (default)
# words_per_minute         : 200
atom_feed:
  # path                   : blank (default) uses feed.xml
  hide                   : true # false (default), true

# search engine
# search                   : false (default), true
# search_full_content      : true, false (default)
# search_provider          : lunr (default), algolia, google
# lunr:
  # search_within_pages    : false (default), true

# SEO Related
# google_site_verification :
# bing_site_verification   :
# naver_site_verification  :
# yandex_site_verification :
# baidu_site_verification  :

# Social Sharing
# twitter:
#   username               :
# facebook:
#   username               :
#   app_id                 :
#   publisher              :
og_image                 : /assets/images/logo/docsimpo-logo-og@2x.png

# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
# social:
  # type                   : Person or Organization (defaults to Person)
  # name                   : If the user or organization name differs from the site's name
  # links: An array of links to social media profiles

# Analytics
# analytics:
  # provider               : false (default), "google", "google-universal", "google-gtag", "custom"
  # google:
  #   tracking_id          :
    # anonymize_ip         : true, false (default)

# Site Author
author:
  name             : "王烨"
  avatar           : "https://avatars.githubusercontent.com/u/38174537?s=400&u=d532db4c31141ce67458174d2dc8b65782a80237&v=4"
  bio              : "敲得动代码、玩得转微积分的技术写作职业选手。"
  location         : "中国 北京"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wongyah"
    - label: "公众号"
      icon: "fab fa-fw fa-weixin"
      url: "https://mp.weixin.qq.com/s?__biz=MzA5NzU4ODAwOQ==&mid=2247487464&idx=1&sn=c57c1b993dcb2c166d88bc2c0d414a10&chksm=909fc9aea7e840b874ebe3e37d0e2a58de7c4c4c5e18f1355b1a4be6378b5752c571c4aeddd4&token=587590048&lang=zh_CN#rd"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/wongyah"
    - label: "公众号"
      icon: "fab fa-fw fa-weixin"
      url: "https://mp.weixin.qq.com/s?__biz=MzA5NzU4ODAwOQ==&mid=2247487464&idx=1&sn=c57c1b993dcb2c166d88bc2c0d414a10&chksm=909fc9aea7e840b874ebe3e37d0e2a58de7c4c4c5e18f1355b1a4be6378b5752c571c4aeddd4&token=587590048&lang=zh_CN#rd"
    - label: "知乎"
      icon: "fab fa-fw fa-zhihu"
      url: "https://www.zhihu.com/column/c_1548252009672929280"
    - label: "邮箱"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:wongyah@126.com?subject=Awesome%20technical%20writing%20learning"

head_scripts:
  - https://code.jquery.com/jquery-3.2.1.min.js
  - "/assets/js/github-alerts.js"
  - https://cdn.bootcdn.net/ajax/libs/mermaid/10.9.0/mermaid.min.js

# Reading Files
include:
  - _pages
exclude:
  - code-of-conduct.md
  - contributing.md
  - license.md

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


defaults:
  - scope:
      path: ""
      type: posts
    values:
        layout: post
        toc: true
        toc_sticky: true
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      # sidebar:
      #   - title: "Wechat Subscription Account"
      #     image: /assets/images/socia-media/qrcode_wechat_258.jpg
      #     image_alt: "Wechat subscription account ID: docSimpo"
      #     text: "Scan the QR code to follow my Wechat subscription account (ID: docSimpo)."


# Plugins
plugins:
  - jekyll-include-cache

# Building
disable_disk_cache: BOOL
sass:
  quiet_deps: true